CREATE TABLE `MEMBER` (
	`MEMBER_SEQ`	INT	NOT NULL,
	`MEMBER_ID`	VARCHAR(100)	NULL,
	`MEMBER_PASSWORD`	VARCHAR(100)	NULL,
	`MEMBER_EMAIL`	VARCHAR(100)	NULL,
	`MEMBER_NAME`	VARCHAR(100)	NULL,
	`MEMBER_NICKNAME`	VARCHAR(100)	NULL,
	`MEMBER_PHONE`	VARCHAR(100)	NULL,
	`MEMBER_PROFILE_IMAGE_URL`	VARCHAR(100)	NULL,
	`MEMBER_DOB`	DATE	NULL,
	`REG_DT`	DATE	NULL
);

CREATE TABLE `NFT` (
	`NFT_HASH`	VARCHAR(100)	NOT NULL,
	`NFT_OWNER_SEQ`	INT	NOT NULL,
	`NFT_CREATOR_SEQ`	INT	NULL,
	`NFT_TYPE`	VARCHAR(100)	NULL,
	`NFT_NAME`	VARCHAR(100)	NULL,
	`NFT_PRICE`	INT	NULL
);

CREATE TABLE `WALLET` (
	`MEMBER_SEQ`	INT	NOT NULL,
	`WALLET_HASH`	VARCHAR(100)	NULL
);

CREATE TABLE `TRANSACTION` (
	`TRANSACTION_SEQ`	INT	NOT NULL,
	`TRANSACNTION_HASH`	VARCHAR(100)	NULL,
	`TRANSACTION_FROM`	VARCHAR(100)	NULL,
	`TRANSACTION_TO`	VARCHAR(100)	NULL,
	`TRANSACTION_VALUE`	VARCHAR(100)	NULL,
	`NFT_HASH`	VARCHAR(100)	NOT NULL,
	`REG_DT`	DATE	NULL
);

CREATE TABLE `BID` (
	`BID_SEQ`	INT	NOT NULL,
	`NFT_HASH`	VARCHAR(100)	NOT NULL,
	`BID_START`	DATE	NULL,
	`BID_END`	DATE	NULL
);

CREATE TABLE `BID_LOG` (
	`BID_SEQ`	INT	NOT NULL,
	`MEMBER_SEQ`	INT	NOT NULL,
	`BID_PRICE`	FLOAT	NULL,
	`REG_DT`	DATE	NULL
);

CREATE TABLE `MEMBER_FOLLW` (
	`FOLLOWER`	INT	NOT NULL,
	`FOLLOWEE`	INT	NULL
);

CREATE TABLE `NFT_LIKE` (
	`MEMBER_SEQ`	INT	NOT NULL,
	`NFT_HASH`	VARCHAR(100)	NOT NULL
);

CREATE TABLE `EXHIBITION` (
	`EXHIBITION_ID`	INT	NOT NULL,
	`MEMBER_SEQ`	INT	NOT NULL,
	`EXHIBITION_TYPE`	CHAR(3)	NULL,
	`EXHIBITION_COMMENT`	VARCHAR(100)	NULL
);

CREATE TABLE `EXHIBITION_WORK` (
	`EXHIBITION_ID`	INT	NOT NULL,
	`NFT_HASH`	VARCHAR(100)	NOT NULL,
	`WORK_COMMENT`	VARCHAR(100)	NULL
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`MEMBER_SEQ`
);

ALTER TABLE `NFT` ADD CONSTRAINT `PK_NFT` PRIMARY KEY (
	`NFT_HASH`
);

ALTER TABLE `WALLET` ADD CONSTRAINT `PK_WALLET` PRIMARY KEY (
	`MEMBER_SEQ`
);

ALTER TABLE `TRANSACTION` ADD CONSTRAINT `PK_TRANSACTION` PRIMARY KEY (
	`TRANSACTION_SEQ`
);

ALTER TABLE `BID` ADD CONSTRAINT `PK_BID` PRIMARY KEY (
	`BID_SEQ`
);

ALTER TABLE `BID_LOG` ADD CONSTRAINT `PK_BID_LOG` PRIMARY KEY (
	`BID_SEQ`
);

ALTER TABLE `MEMBER_FOLLW` ADD CONSTRAINT `PK_MEMBER_FOLLW` PRIMARY KEY (
	`FOLLOWER`
);

ALTER TABLE `NFT_LIKE` ADD CONSTRAINT `PK_NFT_LIKE` PRIMARY KEY (
	`MEMBER_SEQ`,
	`NFT_HASH`
);

ALTER TABLE `EXHIBITION` ADD CONSTRAINT `PK_EXHIBITION` PRIMARY KEY (
	`EXHIBITION_ID`
);

ALTER TABLE `EXHIBITION_WORK` ADD CONSTRAINT `PK_EXHIBITION_WORK` PRIMARY KEY (
	`EXHIBITION_ID`,
	`NFT_HASH`
);

ALTER TABLE `WALLET` ADD CONSTRAINT `FK_MEMBER_TO_WALLET_1` FOREIGN KEY (
	`MEMBER_SEQ`
)
REFERENCES `MEMBER` (
	`MEMBER_SEQ`
);

ALTER TABLE `BID_LOG` ADD CONSTRAINT `FK_BID_TO_BID_LOG_1` FOREIGN KEY (
	`BID_SEQ`
)
REFERENCES `BID` (
	`BID_SEQ`
);

ALTER TABLE `MEMBER_FOLLW` ADD CONSTRAINT `FK_MEMBER_TO_MEMBER_FOLLW_1` FOREIGN KEY (
	`FOLLOWER`
)
REFERENCES `MEMBER` (
	`MEMBER_SEQ`
);

ALTER TABLE `NFT_LIKE` ADD CONSTRAINT `FK_MEMBER_TO_NFT_LIKE_1` FOREIGN KEY (
	`MEMBER_SEQ`
)
REFERENCES `MEMBER` (
	`MEMBER_SEQ`
);

ALTER TABLE `NFT_LIKE` ADD CONSTRAINT `FK_NFT_TO_NFT_LIKE_1` FOREIGN KEY (
	`NFT_HASH`
)
REFERENCES `NFT` (
	`NFT_HASH`
);

ALTER TABLE `EXHIBITION_WORK` ADD CONSTRAINT `FK_EXHIBITION_TO_EXHIBITION_WORK_1` FOREIGN KEY (
	`EXHIBITION_ID`
)
REFERENCES `EXHIBITION` (
	`EXHIBITION_ID`
);

ALTER TABLE `EXHIBITION_WORK` ADD CONSTRAINT `FK_NFT_TO_EXHIBITION_WORK_1` FOREIGN KEY (
	`NFT_HASH`
)
REFERENCES `NFT` (
	`NFT_HASH`
);

