CREATE TABLE `MEMBER` (
	`MEMBER_SEQ`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`MEMBER_ID`	VARCHAR(100)	NOT NULL UNIQUE,
	`MEMBER_PASSWORD`	VARCHAR(100)	NOT NULL,
	`MEMBER_EMAIL`	VARCHAR(100)	NOT NULL UNIQUE,
	`MEMBER_NAME`	VARCHAR(100)	NOT NULL,
	`MEMBER_NICKNAME`	VARCHAR(100)	NOT NULL,
	`MEMBER_PHONE`	VARCHAR(100)	NOT NULL UNIQUE,
	`MEMBER_PROFILE_IMAGE_URL`	VARCHAR(100)	DEFAULT 'IMAGE/NOIMAGE.PNG',
	`MEMBER_DOB`	DATE	NOT NULL,
	`MEMBER_ENABLE` BOOLEAN,
	`REG_DT`	TIMESTAMP	NOT NULL
);

CREATE TABLE `NFT` (
	`NFT_HASH`	VARCHAR(100)	NOT NULL PRIMARY KEY,
	`NFT_OWNER_SEQ`	INT	NOT NULL,
	`NFT_CREATOR_SEQ`	INT	NOT NULL,
	`NFT_TYPE`	VARCHAR(100)	NOT NULL,
	`NFT_NAME`	VARCHAR(100)	NOT NULL
);

CREATE TABLE `WALLET` (
	`WALLET_HASH`	VARCHAR(100)	NOT NULL PRIMARY KEY,
	`MEMBER_SEQ`	INT	NOT NULL
);

CREATE TABLE `TRANSACTION` (
	`TRANSACTION_SEQ`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TRANSACNTION_HASH`	VARCHAR(100)	NOT NULL UNIQUE,
	`TRANSACTION_FROM`	VARCHAR(100)	NOT NULL,
	`TRANSACTION_TO`	VARCHAR(100)	NOT NULL,
	`TRANSACTION_VALUE`	VARCHAR(100)	NOT NULL,
	`NFT_HASH`	VARCHAR(100)	NOT NULL,
	`REG_DT`	TIMESTAMP	NOT NULL
);

CREATE TABLE `BID` (
	`BID_SEQ`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NFT_HASH`	VARCHAR(100)	NOT NULL,
	`BID_START`	DATE	NOT NULL,
	`BID_END`		DATE	NOT NULL,
	`BID_MAX_PRICE`	FLOAT	NOT NULL
);

CREATE TABLE `BID_LOG` (
	`BID_LOG_SEQ` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`BID_SEQ`	INT	NOT NULL,
	`MEMBER_SEQ`	INT	NOT NULL,
	`BID_PRICE`	FLOAT	NOT NULL,
	`REG_DT`	TIMESTAMP	NOT NULL
);

CREATE TABLE `MEMBER_FOLLOW` (
	`FOLLOWER`	INT	NOT NULL,
	`FOLLOWEE`	INT	NOT NULL
);

CREATE TABLE `NFT_FAVORITE` (
	`MEMBER_SEQ`	INT	NOT NULL,
	`NFT_HASH`	VARCHAR(100)	NOT NULL
);

CREATE TABLE `EXHIBITION` (
	`EXHIBITION_SEQ`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`MEMBER_SEQ`	INT	NOT NULL,
	`EXHIBITION_TYPE`	CHAR(3)	NOT NULL,
	`EXHIBITION_COMMENT`	VARCHAR(100)	NULL
);

CREATE TABLE `EXHIBITION_WORK` (
	`EXHIBITION_SEQ`	INT	NOT NULL,
	`NFT_HASH`	VARCHAR(100)	NOT NULL,
	`WORK_COMMENT`	VARCHAR(100)	NULL
);

CREATE TABLE `TRADE` (
	`TRADE_SEQ`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NFT_HASH`	VARCHAR(100)	NOT NULL,
	`NFT_OWNER_SEQ`	INT	NOT NULL,
	`TARDE_PRICE`	FLOAT	NOT NULL,
	`REG_DT`	TIMESTAMP	NOT NULL
);

ALTER TABLE `NFT_FAVORITE` ADD CONSTRAINT `PK_NFT_FAVORITE` PRIMARY KEY (
	`MEMBER_SEQ`,
	`NFT_HASH`
);

ALTER TABLE `MEMBER_FOLLOW` ADD CONSTRAINT `FK_MEMBER_TO_MEMBER_FOLLOW_1` FOREIGN KEY (
	`FOLLOWER`
)
REFERENCES `MEMBER` (
	`MEMBER_SEQ`
);

ALTER TABLE `NFT_FAVORITE` ADD CONSTRAINT `FK_MEMBER_TO_NFT_FAVORITE_1` FOREIGN KEY (
	`MEMBER_SEQ`
)
REFERENCES `MEMBER` (
	`MEMBER_SEQ`
);

ALTER TABLE `NFT_FAVORITE` ADD CONSTRAINT `FK_NFT_TO_NFT_FAVORITE_1` FOREIGN KEY (
	`NFT_HASH`
)
REFERENCES `NFT` (
	`NFT_HASH`
);

ALTER TABLE `EXHIBITION_WORK` ADD CONSTRAINT `FK_EXHIBITION_TO_EXHIBITION_WORK_1` FOREIGN KEY (
	`EXHIBITION_SEQ`
)
REFERENCES `EXHIBITION` (
	`EXHIBITION_SEQ`
);

ALTER TABLE `EXHIBITION_WORK` ADD CONSTRAINT `FK_NFT_TO_EXHIBITION_WORK_1` FOREIGN KEY (
	`NFT_HASH`
)
REFERENCES `NFT` (
	`NFT_HASH`
);

